### PR TITLE
Implement Partner Stats API authentication

### PR DESCRIPTION
**Pull request by beheh**
This is work towards #861.

### CODE REVIEW

**Comment by beheh** [comment]
@joolean What do you think about moving the Partner Stats API under the same URL path as our existing API? Was there a reason the spec specified a separate path?

**Comment by joolean** [comment]
@beheh Yeah, the reason was that it's effectively a separate "product." Our strategy for sharing it and, in particular, versioning it will be different. 

It seemed to me that it would be easier to, for example, keep the partner stats API at "v1" even as the primary HSReplay.net API was moving to "v2," if "partner" was the root partition of the URL path. But I guess I don't feel that strongly about it - it's certainly possible to keep the partner API under "/api/v1/partner-stats/" even if "/api/v1/some-other-thing" has been deprecated in favor of "/api/v2/some-other-thing".

**Comment by beheh** [comment]
I think this pattern is easy enough to change apart down the line anway, as it mostly just dictates where the code will live. If we decide to significantly change the way the API behaves or massively increase it's complexity past the current API we can still split it up with relative ease. The URL can be configured independantly as well.

Additionally, it looks like most of the APIs configuration is done either globally (using a setting) or on a per view level (using properties) anyway. So even if we set up a separate app we would be using the same API defaults for authentication and authorization as the main API if we used the settings way, unless we want to add something like django-appconf.

For the time being then I'll move the code to the `api` app and keep the partner stats views in their own file.

**Comment by joolean** [comment]
Well, note that we'll be giving the URL out to partners and for that reason it won't be trivial to change later. So we are making a bit of a commitment here.

**Comment by beheh** [comment]
Sure, although I was specifically talking about the Django app here. The URL can be configured irregardless of Django app, so even if we decide to move it to another app we'd be keeping the URL.

**Comment by jleclanche** [comment]
There's no real reason why the URL should be outside of the /api/ namespace, and there's a few very good reasons why it shouldn't be. More specifically, the /api/v1/ path is already set up here as a pass-through: https://api.hsreplay.net/v1/

Whatever URLs we give, they *have* to be on a separate subdomain if we want it to be easy to put it on different servers in the future, without a hard dependency on cloudfront. This is the reason api.hsreplay.net exists and I believe all our non-website clients are using api.hsreplay.net right now.

**Comment by jleclanche** [comment]
The plan fwiw was to have different authentication methods for hsr/api/ and api.hsr. /api/ would be session-only auth and enforce CSRF. Again, similar setup as Stripe's.

**Comment by beheh** [comment]
There seem to be 3 proposals that diverge from the ticket right now:

1. Should the code live in the existing `api` Django app, or in a new app (such as `partner`)
2. Should we host the API under `/api`, or something else (such as `/partner`). Either way we'd be publishing the `api.hsreplay.net` domain.
3. Should we use our own featuretag system instead of Django model permissions

I've rethought my stance on 1. and want us to use a separate Django app. There are a few reasons:
- **Product Management**: The API is fundamentally a different product than our "main" API. While the main API fully relies on Session Authentication and has both user-scoped and global parts, the partner API is multi-user, read-only and access is achieved very differently, namely by us granting explicit access. The access patterns are also very different, and they do not scale in the same way (site users vs. external partners). And finally, the SLAs look very different: where one is our own userbase on a day-by-day basis where we're fully responsible ourselves if things break, the partner API makes third parties dependent on us.
- **Technical**: There is no reason to co-locate the code for our main API and the partner API, and it brings with it the danger of introducing unnecessary dependencies and locking us into the same framework. While the current plan is to use DRF for both, I can see us switching either API to a different framework, also because of the strongly different usage and access patterns. I do not want a change or upgrade in either API to block work on the other one.

I agree with proposal 3., due to us somewhat misusing the permission system by using it outside of a model context. For that, we'd need a seemingly fragile workaround with a virtual, non-managed modal. We also barely use that authentication framework. 

For now, I will proceed as follows:
- Keep the current PR's state of using a separate `partner` app
- Keep the current PR's use of a separate URL path namespace (`/partner-stats/v1/`)
- Replace the Django model permission commit with one using our featuretag system

**Comment by jleclanche** [comment]
This doesn't need to be a separate app at all and there's been a lot of efforts to clean up the divergence in apps. Apps in Django have a lot of esoteric machinery behind them, such as gathering of admin apps, url namespacing, models and model namespacing, etc which are not relevant for this.
If you want it to be a python *module*, such as `api.partner`, that's also fine and doesn't involve such machinery. There's no problem with the code itself being split.

Re url I agree this is solvable later.

**Pull request merged**
