### PR TITLE
Handle timeout during encoding validation in upload processing

### PR DESCRIPTION
**Pull request by joolean**

### CODE REVIEW

**Comment by beheh** [comment]
Doesn't the [`max_attempts`](https://botocore.readthedocs.io/en/latest/reference/config.html) from boto3 apply here anyway?

Not a huge fan of this hardcoded single retry, as opposed to some configurable options. It also looks like the default timeout is two minutes, so in case S3 were slow we're blocking up two two minutes on the validation (and potentially further in the later processing stages), That seems dangerous, as we only have 5 minutes for the whole lambdas. Maybe set a more aggressively timeout here?

**Comment by jleclanche** [comment]
Agreed with @beheh, there's already native retries, those are the ones we should rely on. If it still fails afterwards, we can safely stop retrying and do so later.

**Comment by beheh** [comment]
Looking at the exception I don't think boto retried though. For the sake of this PR we could investigate that setting.

**Comment by joolean** [comment]
Here's an alternate way of configuring the retry. I'm still trying to add a test to exercise the retry, but there's something very wrong and frustrating with our pytest transactions such that they stay open throughout the entire module instead of rolling back after each test function.

**Pull request merged**
